---
- hosts: all
  tasks:
    - name: Homebrew Gone
      file:
        path: /usr/local/Homebrew
        state: absent

- hosts: all
  name: Configure MacOS workers
  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: worker
