---
- name: Initialise opam
  command: opam init -y
  register: opaminit
- debug: msg="{{ opaminit }}"
- name: Pin opam-sysinstall
  command: "opam pin add opam-sysinstall git+https://github.com/patricoferris/opam-sysinstall --yes"
- name: Install opam
  command: opam install opam-sysinstall --yes
- name: Opam System Compilers Directory
  file:
    path: "/var/ocaml"
    state: directory
- name: Install a system compiler
  command: opam exec -- opam sysinstall build --latest=4 --prefix="/var/ocaml" --jobs=8
- name: System compilers 
  command: "ls /var/ocaml"
  register: syscomp
- debug: msg="{{ syscomp }}"
- name: Get OCluster
  git: 
    repo: 'https://github.com/patricoferris/ocluster.git'
    dest: '/var/ocluster'
    clone: true
    recursive: true
