---
# Mostly taken from geerlingguy/mac-dev-playbook
name: Ansible testing
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  ansible:
    name: Ansible setup
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./tests/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install test dependencies.
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip3 install -r ./tests/requirements.txt
      - name: Lint code
        run: |
          yamllint .
          ansible-lint
      - name: Remove Homebrew
        run: ./.github/workflows/uninstall-homebrew.sh
      - name: Install ansible
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo pip3 install -r ./tests/requirements.txt
      - name: Copy in test configuration
        run: |
          cp ./tests/hosts ./hosts
      - name: Syntax checker
        run: ansible-playbook main.yml --syntax-check
      - name: TODO
        run: echo "More coming soon!"
